### ISSUE TITLE
[CONTRACTS] add `register` endpoint

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#10]
create the `register` endpoint, implement the registration logic without verifying the zk-SNARK proof ot it

**Comment by chachaleo** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkramp).

### My background and how it can be leveraged
Mathematics engineering and zkml Cairo dev, I'm usually not this kind of dev but I have xp in Cairo

**Comment by HumbertoTM10** [comment]
Hi @0xChqrles I'm diving more into zk-SNARKs and would like to work on this.

**Comment by 0xChqrles** [comment]
Hey @HumbertoTM10 This issue and the ones to follow in the coming days will not be related to the verification of SNARKs in Cairo. But I'll keep everyone updated in the Telegram group when it happens!

**Comment by 0xChqrles** [comment]
@chachaleo glad to have you on the project! I've assigned you to this issue, lmk if you have any questions
