### ISSUE TITLE
[CI] setup tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#16]
Setup the CI to do these test on each PR:

- cairo test
- cairo fmt
- website lint
- client lint
- extension lint

**Comment by Ayoazeez26** [comment]
Hi @0xChqrles can I pick this up?

**Comment by 0xChqrles** [comment]
Hey @Ayoazeez26 ! You're already assigned to #3 ^^

**Comment by addegbenga** [comment]
Can i work on this

**Comment by luiz-lvj** [comment]
Hello! I'm interested in this one!

**Comment by 0xChqrles** [comment]
If you need an example, [this project](https://github.com/keep-starknet-strange/vault) has a similar CI

**Comment by luiz-lvj** [comment]
> If you need an example, [this project](https://github.com/keep-starknet-strange/vault) has a similar CI

Thanks! I'll take a look
