### ISSUE TITLE
[CLIENT] Currency input component

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#3]
Create a currency input component similar to what Uniswap have, without the possibility to select a specific token.

**Comment by Ayoazeez26** [comment]
@0xChqrles can I work on this

**Comment by 0xChqrles** [comment]
Hey @Ayoazeez26 ! Please fill the Only Dust application to help me better distribute the issues ^^

**Comment by 0xChqrles** [comment]
Thanks ! I've assigned you to it @Ayoazeez26
