### ISSUE TITLE
[CONTRACTS] nullifier_registry contract functions

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/zkramp#31]
### Description

In `contracts/src/contracts/nullifier_registry` add the following functions to the `nullifier_registry.cairo` contract: 

- [ ] add_nullifier 
- [ ] add_write_permissions
- [ ] remove_write_permissions
- [ ] get_writers

These require storage items: mappings for nullifiers and writers. Span for writers.
Emit an event for each function that makes changes to the storage.

Add tests for expected storage changes and getter functions. 

For reference see the [Solidity implementation](https://github.com/zkp2p/zk-p2p/blob/28614160b5f1320c4b866ee41d11b186f9693aab/contracts/contracts/processors/nullifierRegistries/NullifierRegistry.sol) of zkp2p. 

### Acceptance criteria

The contract builds. It emits the corresponding event for each function. Tests pass.

**Comment by mubarak23** [comment]
Yes

**Comment by manlikeHB** [comment]
Hi @lana-shanghai .
