### ISSUE TITLE
[CONTRACTS] Check Eth signature in TLS processor contract

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/zkramp#34]
### Description 

For compatibility with the zkp2p Notary node, we will use Ethereum keys when signing messages. 

Reimplement [this](https://github.com/zkp2p/zk-p2p/blob/28614160b5f1320c4b866ee41d11b186f9693aab/contracts/contracts/processors/TLSBaseProcessor.sol#L94) `is_valid_signature` method from Solidity. 

Reuse OpenZeppelin's `is_valid_eth_signature` [method](https://github.com/OpenZeppelin/cairo-contracts/blob/main/packages/account/src/utils/signature.cairo#L36) in the [TLS](https://github.com/keep-starknet-strange/zkramp/blob/main/contracts/src/components/processors/tls/tls.cairo#L119) processor in Cairo.

### Acceptance criteria

Test that correct signatures pass, and incorrect signatures fail.

**Comment by luiz-lvj** [comment]
I'd like to take this one
