### ISSUE TITLE
[CONTRACTS] Create generic escrow component 

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#38]

**Comment by manlikeHB** [comment]
hi @0xChqrles , can i work on this?

**Comment by chachaleo** [comment]
Hey, can I work on this ? :)

**Comment by lana-shanghai** [comment]
To implement the escrow contract component, we need the following functionality: 

- a storage item holding the deposited funds, each item with information about the buyer and seller side, value, and timelock;
- a function to add a new deposit; 
- a function to release funds by the buyer with a `//TODO` to add a check for proof of deposit via Revolut by the seller, currently just leave a dummy check returning true by default 
- a function to claim back the funds by the seller if the timelock passed (after the number of blocks passed) 
- removal of the deposit tracking item from the storage
