### ISSUE TITLE
[CLIENT] setup a swap page

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#4]
Setup a swapping page, to swap USDC / Fiat.

Use the component created by #3

**Comment by 0xChqrles** [comment]
Hey @mexes20 ! Please fill the Only Dust application to help me better distribute the issues ^^

**Comment by ugur-eren** [comment]
Hi @0xChqrles I would love to work on this!

**Comment by 0xChqrles** [comment]
Hi @mexes20 I'm sorry but I'm going to assign this issue to @ugur-eren I'm familiar with his work and this is quite an important and blocking issue. However, I invite you to contact me on Telegram. You can find the group link in the README so that I can find you a first issue to work on for the project.
