### ISSUE TITLE
[INDEXER] index zkRamp deposits/withdrawals

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#40]
(choose between Apibara and Dipdup)

**Comment by EjembiEmmanuel** [comment]
@0xChqrles I'd love to work on this

**Comment by ugur-eren** [comment]
Hi, I would love to work on this if it's available

**Comment by lana-shanghai** [comment]
Hey @EjembiEmmanuel you can, but this task depends on [issue](https://github.com/keep-starknet-strange/zkramp/issues/41) once the events are emitted, you'll be able to index them. I will assign you and then you can sync with Mubarak :)

**Comment by EjembiEmmanuel** [comment]
Thank you @lana-shanghai

**Comment by 0xChqrles** [comment]
Hey @EjembiEmmanuel ! Sorry to have to do this, but to meet the milestone 01 deadline, I would prefer to assign the issue to @ugur-eren, with whom I have already worked on the unruggable memecoin indexer.

@EjembiEmmanuel reach me out on tg to find you another issue to work on
