### ISSUE TITLE
[CONTRACTS] add events logic to the escrow

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#41]

**Comment by mubarak23** [comment]
@0xChqrles can i work on this,

**Comment by lana-shanghai** [comment]
Hey @mubarak23 ! This issue depends on this component [issue](https://github.com/keep-starknet-strange/zkramp/issues/38) please sync with @chachaleo as she is assigned to it. What's the ETA?
Next, the indexer [issue](https://github.com/keep-starknet-strange/zkramp/issues/40) depends on the events issue assigned to you. Please also sync with Ejembi.

**Comment by mubarak23** [comment]
@0xChqrles can you close this, it has been completed already
