### ISSUE TITLE
[CLIENT] setup registration page

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#5]
setup the page to link you revolut account to you starknet address.

Do not create the actual logic, just the UI/UX

**Comment by Calebux** [comment]
I'll like to take this up

**Comment by BlackStarkGoku** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/zkramp).

### My background and how it can be leveraged
Hello, I am a Full-Stack software engineer with cairo and Typescript, this can be solved using tailwind

### How I plan on tackling this issue
 I would check the design If there is one or just follow the visual aspect of the app to implement this.

**Comment by 0xChqrles** [comment]
@BlackStarkGoku Glad to see you here ! I'll assign you to this issue, lmk if you have any question

@Calebux Don't worry many other issues are coming in, just provide more details in your message next time, it's helpful for me to know who to assign the issues to ^^
