### ISSUE TITLE
[CONTRACT] add lock duration logic to the escrow

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#51]
The `lock` function of the escrow should take as a parameter a minimum lock duration expressed in seconds.

The verification of compliance with this duration will be implemented later in a hook.

---

This way, a user who locks an amount in USDC must wait for a certain period before being able to withdraw their funds if no one has agreed to the exchange. However, a user who provides proof of an off-chain transfer can withdraw the funds without waiting.

**Comment by mubarak23** [comment]
I
