### ISSUE TITLE
[BACKEND] add `get_offramp_quotes` endpoint

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#55]
waiting for #53 and #40 to be completed first

**Comment by Gerson2102** [comment]
Can this be a good first issue?

**Comment by Jemiiah** [comment]
@0xChqrles I would love to work on this issue seems like the current assigned is no longer interested in it . I would handle it

**Comment by Gerson2102** [comment]
Of course I'm still interested. As far as i know this issue is blocked. Thats the reason I haven't start it yet.

**Comment by Jemiiah** [comment]
ohh okay mybad then @Gerson2102
