### ISSUE TITLE
[EXTENSION] setup the sidebar extension

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#6]
Setup the extension in the monorepo. Use a stack as similar as possible as the one already used for the client.

**Comment by ugur-eren** [comment]
Hi @0xChqrles I would want to work on this.
I can create a repo and setup extension and initialize it with React or any other framework of choice.

**Comment by 0xChqrles** [comment]
@ugur-eren I just did it 😅 But it unlocks new issues related to the extension then ! I'll assign you to one of them
