### ISSUE TITLE
[CONTRACT] integrate registration component

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#64]
Create the zkRamp contract integration the registry component.

---

**Please add integration tests**

**Comment by Jemiiah** [comment]
@0xChqrles i would love to work on this issue

**Comment by mubarak23** [comment]
@0xChqrles can I work on this, I already understand how contract structure works

**Comment by 0xChqrles** [comment]
Hey ! I assigned it to you @Jemiiah
