### ISSUE TITLE
[CONTRACT] setup liquidity addition

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#65]
Complete this issue according to this article: [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

---

**Please add integration tests**

**Comment by mubarak23** [comment]
@0xChqrles i

**Comment by manlikeHB** [comment]
Hi @0xChqrles, an i work on this?

**Comment by ugur-eren** [comment]
Hi @0xChqrles Can i work on this issue if it's available?

**Comment by ikemHood** [comment]
Hey @0xChqrles I would like to work on this so I can work on #67 which is a dependant.

**Comment by manlikeHB** [comment]
@0xChqrles, can I work on this?

**Comment by mubarak23** [comment]
> @0xChqrles am available to work on this ,
> 
> With previous experience working on this codebase,
> 
> I have read the article
> 
> I can implement this with 3 days
> 
> ETH: 72hrs

@0xChqrles am available to work on this
