### ISSUE TITLE
[CONTRACT] setup liquidity retrieval

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#66]
Complete this issue according to this article: [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

---

**Please add integration tests**

**Comment by Jemiiah** [comment]
@0xChqrles I would love to work on this issue !!

**Comment by TropicalDog17** [comment]
Hi, can I work on this issue? I've contributed to various Cairo projects and am confident to tackle this.

**Comment by manlikeHB** [comment]
Hi @0xChqrles ,  I have read through the attach article and with a little bit research on my part, I can implement this.

**Comment by mubarak23** [comment]
@0xChqrles having read the article, and my understanding of the codebase. 

I will implement this issue 


ETH: 48hrs

**Comment by chachaleo** [comment]
Heyy can I work on this ? :)
