### ISSUE TITLE
[CONTRACT] setup liquidity share request without proof verification

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#67]
Complete this issue according to this article: [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

---

**Please add integration tests**

**Comment by mubarak23** [comment]
@0xChqrles Am available to work on this , kindly assign

**Comment by stevencartavia** [comment]
Hi, I would like to try this!

**Comment by mubarak23** [comment]
@0xChqrles am available for this one

**Comment by manlikeHB** [comment]
Hi @0xChqrles,  I have read through the attach article and with a little bit research on my part, I can implement this.

**Comment by ikemHood** [comment]
Hello @0xChqrles , I would like to work on this issue,

here is how i would handle it...

1. I will define a Storage struct `LiquidityPosition` to store liquidity positions` and a counter for position IDs.
2. I will create `LiquidityAdded` and `WithdrawalInitiated` events to emit when these actions occur.
3. Implement a `add_liquidity` function
4. Implement the `initiate_liquidity_withdrawal` function
5. perform unit tests

ETA: 72hrs

**Comment by 0xChqrles** [comment]
Hey @ikemHood I assigned it to you. Join the project's Telegram group if you haven't already, and feel free to ask any questions. Also, you'll need to wait for issue #65 and #66 to be merged before you can start on this one.
