### ISSUE TITLE
[CONTRACT] create zkRamp paymaster account contract

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#68]
Use the Vault [SNIP-9](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-9.md) [implementation](https://github.com/keep-starknet-strange/vault/tree/main/onchain/src/components/outside_execution) to create the account that will be used by zkRamp as paymaster

---

**Please add unit and integration tests**

**Comment by mubarak23** [comment]
I work on something like this on Joyboy project . @0xChqrles kindly assigned
