### ISSUE TITLE
[CONTRACTS] implement `retrieve_liquidity` tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#85]
The tests are already defined in `src/contracts/ramps/revolut/revolut_test.cairo`. You just need to write their implementation following the way the escrow tests are implemented.

These contracts will be holding funds, so it's of utmost importance that the tests cover 100% of possible use cases, are readable, easily modifiable, and consistent.

To better understand how the contracts work, please read this article [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

These tests are also related to #84

**Comment by chachaleo** [comment]
can I work on this ? :)

**Comment by Jemiiah** [comment]
I would love for work on this @0xChqrles

**Comment by thesledge04** [comment]
hey @0xChqrles can i be assigned this task?

**Comment by leohscl** [comment]
I would like to get this one please
