### ISSUE TITLE
[CONTRACTS] implement `initiate_liquidity_withdraw` tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#86]
The tests are already defined in `src/contracts/ramps/revolut/revolut_test.cairo`. You just need to write their implementation following the way the escrow tests are implemented.

These contracts will be holding funds, so it's of utmost importance that the tests cover 100% of possible use cases, are readable, easily modifiable, and consistent.

To better understand how the contracts work, please read this article [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

**Comment by mubarak23** [comment]
q

**Comment by Oshioke-Salaki** [comment]
Please can I handle this?

**Comment by ikemHood** [comment]
hello @0xChqrles , I would love to work on this

**Comment by od-hunter** [comment]
Hi @0xChqrles , can I work on this please? Please

**Comment by Benjtalkshow** [comment]
Hello @0xChqrles ,
Can I be assigned to this? I can tackle this issue asap.
