### ISSUE TITLE
[CONTRACTS] implement `withdraw_liquidity` tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#87]
implementation following the way the escrow tests are implemented.

These contracts will be holding funds, so it's of utmost importance that the tests cover 100% of possible use cases, are readable, easily modifiable, and consistent.

To better understand how the contracts work, please read this article [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

These tests are also related to #86

**Comment by mubarak23** [comment]
q

**Comment by Oshioke-Salaki** [comment]
Please can I do this?

**Comment by ikemHood** [comment]
Hello @0xChqrles , can i also do this one

**Comment by thesledge04** [comment]
hello @0xChqrles can i be assigned this task?

**Comment by chachaleo** [comment]
Can I work on this ? :)
