### ISSUE TITLE
[CONTRACTS] implement `available_liquidity` tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#89]
The tests are already defined in `src/contracts/ramps/revolut/revolut_test.cairo`. You just need to write their implementation following the way the escrow tests are implemented.

These contracts will be holding funds, so it's of utmost importance that the tests cover 100% of possible use cases, are readable, easily modifiable, and consistent.

To better understand how the contracts work, please read this article [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

**Comment by mubarak23** [comment]
w

**Comment by Jemiiah** [comment]
i

**Comment by manlikeHB** [comment]
Can I work on this?

**Comment by ScottyDavies** [comment]
@0xChqrles can i hop on this?

**Comment by leohscl** [comment]
I'm up for this one @0xChqrles
