### ISSUE TITLE
[CONTRACTS] implement `_get_available_liquidity` tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#90]
The tests are already defined in `src/contracts/ramps/revolut/revolut_test.cairo`. You just need to write their implementation following the way the escrow tests are implemented.

These contracts will be holding funds, so it's of utmost importance that the tests cover 100% of possible use cases, are readable, easily modifiable, and consistent.

To better understand how the contracts work, please read this article [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

These tests are also related to #89

**Comment by mubarak23** [comment]
w

**Comment by od-hunter** [comment]
Hi @0xChqrles , can I work on this please?

**Comment by Benjtalkshow** [comment]
Hello @0xChqrles ,
Can I be assigned to this? I can tackle this issue asap.

**Comment by Gift-Naomi** [comment]
@0xChqrles can I work on this?

**Comment by Akshola00** [comment]
@0xChqrles Hi, Im available to work on this

**Comment by leohscl** [comment]
I'm up for this one @0xChqrles
