### ISSUE TITLE
[CONTRACTS] implement `all_liquidity` tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#91]
The tests are already defined in `src/contracts/ramps/revolut/revolut_test.cairo`. You just need to write their implementation following the way the escrow tests are implemented.

These contracts will be holding funds, so it's of utmost importance that the tests cover 100% of possible use cases, are readable, easily modifiable, and consistent.

To better understand how the contracts work, please read this article [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

**Comment by manlikeHB** [comment]
can i work on this?

**Comment by ShantelPeters** [comment]
Hi @0xChqrles i will like to work on this issue

**Comment by Iwueseiter** [comment]
Hi @0xChqrles can I tackle this Issue?

**Comment by Benjtalkshow** [comment]
Hello @0xChqrles ,
Can I be assigned to this? I can tackle this issue asap.

**Comment by thesledge04** [comment]
hey @0xChqrles can i be assigned this task?

**Comment by chachaleo** [comment]
Can I work on this? :)
