### ISSUE TITLE
[CONTRACTS] implement `liquidity_share_request` tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#92]
The tests are already defined in `src/contracts/ramps/revolut/revolut_test.cairo`. You just need to write their implementation following the way the escrow tests are implemented.

These contracts will be holding funds, so it's of utmost importance that the tests cover 100% of possible use cases, are readable, easily modifiable, and consistent.

To better understand how the contracts work, please read this article [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

**Comment by Calebux** [comment]
w

**Comment by manlikeHB** [comment]
can I work on this?

**Comment by Benjtalkshow** [comment]
Hello @0xChqrles ,
Can I be assigned to this? I can tackle this issue asap.

**Comment by ScottyDavies** [comment]
hello @0xChqrles can i please be assigned this task?

**Comment by thesledge04** [comment]
hello @0xChqrles can i be assigned this project?

**Comment by guha-rahul** [comment]
hey @0xChqrles new contributooor here, can i work on this?

**Comment by mubarak23** [comment]
@0xChqrles can i work on this

**Comment by chachaleo** [comment]
Can I work on this? :)

**Comment by Benjtalkshow** [comment]
@0xChqrles can i work on this please?
