### ISSUE TITLE
[CONTRACTS] implement `register` and `is_registered` tests

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#93]
The tests are already defined in `src/components/registry/registry_test.cairo`. You just need to write their implementation following the way the escrow tests are implemented.

These contracts will be holding funds, so it's of utmost importance that the tests cover 100% of possible use cases, are readable, easily modifiable, and consistent.

To better understand how the contracts work, please read this article [How to manage liquidity in a P2P ramping app](https://medium.com/@zkramp/how-to-manage-liquidity-in-a-p2p-ramping-app-e859115bb461)

**Comment by ShantelPeters** [comment]
Kindly assign @0xChqrles

**Comment by TropicalDog17** [comment]
Hi @0xChqrles can I work on this issue, I have experience in Cairo and Rust, and I am confident to complete the task.

https://github.com/keep-starknet-strange/raito/pull/196/
https://github.com/near/near-sdk-rs/pull/1220

**Comment by PavitraAgarwal21** [comment]
Hey can I work on this

**Comment by raizo07** [comment]
@0xChqrles Hello, can I be assigned to work on this?

**Comment by Benjtalkshow** [comment]
Hello @0xChqrles ,
Can I be assigned to this? I can tackle this issue asap.

**Comment by thesledge04** [comment]
hello @0xChqrles can i be assigned this task?
