### ISSUE TITLE
[CLIENT] create new swap component

### ISSUE THREAD

**Issue by 0xChqrles** [keep-starknet-strange/zkramp#99]
see figma for more details

**Comment by Iwueseiter** [comment]
Hi @0xChqrles can I implement this?

**Comment by ugur-eren** [comment]
Hi @0xChqrles I would love to work on this if it's available

**Comment by IamEnergyI** [comment]
Hi @0xChqrles i will like to work on this. 
Following the Figma design.  Thank you

**Comment by supreme2580** [comment]
Hi @0xChqrles can I be assigned to this?

**Comment by ikemHood** [comment]
Hey @0xChqrles, I can get a swap component out in 24-48hrs.

Can you please share the figma link and assign
